// <auto-generated />
namespace ShauliProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Address2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Address2));
        
        string IMigrationMetadata.Id
        {
            get { return "201709261429066_Address2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
